name: Build And Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v7

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir la imagen Docker
        run: docker build -t juanfr97/512-pet-radar-api:latest .

      - name: Publicar imagen en Docker hub
        run: docker push juanfr97/512-pet-radar-api:latest